### ISSUE TITLE
E164Provider.safe_e164 produces incompatible phone numbers

### ISSUE THREAD

**Issue by mattjegan** [crowdcomms/faker-e164#7]
I've recently been using [Django Phone Number Field](https://github.com/stefanfoulis/django-phonenumber-field) and have found that in my tests, using `fake.safe_e164()` is occasionally trigging a validation error from the [`PhoneNumberField` serializer field](https://github.com/stefanfoulis/django-phonenumber-field/blob/master/phonenumber_field/serializerfields.py).

I'll need to do some more testing to find the exact values that are causing this as it might be an issue for the library rather than this provider but thought it was worth reporting.

**Comment by aljp** [comment]
Hmmm, so safe_e164 just returns a number from a predefined list of safe numbers `faker_e164.providers.safe_numbers` which I have taken from https://fakenumber.org/

There aren't many safe numbers to choose from, but it would seem one of those numbers is invalid (or has become invalid?) for the `phonenumbers.parse` method.

**Comment by mattjegan** [comment]
Ok cool, I'll do some further testing when I get time to determine which it is.

**Comment by mattjegan** [comment]
@aljp I have tracked down at least 2 numbers that cause the invalidation: `+441632960979` and `+441632960570`

**Comment by mattjegan** [comment]
@aljp we can probably close this actually. I just noticed in the providers header comments that we knew about this ages ago. I'll make a PR into the readme to make it more prominent though.
